SignalRChat/Pages/CollabSpace.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SignalRChat.Pages.DataClasses;
using SignalRChat.Pages.DB;
using System.ComponentModel.DataAnnotations;

namespace SignalRChat.Pages
{
    public class CollabSpaceModel : PageModel
    {
        [BindProperty]
        [Required(ErrorMessage = "Collaboration Name is required")]
        public string CollaborationName { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Collaboration Notes are required")]
        public string CollaborationNotes { get; set; }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                return Page();
            }
            else
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("Index");
            }
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                // If model state is not valid, return to the page
                return Page();
            }

            // Create a new Collaboration object
            var collaboration = new Collaboration
            {
                CollaborationName = CollaborationName,
                NotesAndInformation = CollaborationNotes
            };

            // Insert the collaboration into the database
            DBClass.InsertCollaboration(collaboration);

            // Redirect to the CollabHub page or any other page as needed
            return RedirectToPage("CollabHub");
        }

        /*POPULATE BUTTON*/
        public IActionResult OnPostPopulateButton()
        {
            if (!ModelState.IsValid)
            {
                ModelState.Clear(); // Causes Model Validation to be skipped and reset for next entry
                CollaborationName = "Team Project 1";
                CollaborationNotes = "We will finish this project ultra ultra quickly!";
            }
            return Page();
        }

        /*CLEAR BUTTON*/
        public IActionResult OnPostClearButton()
        {
            if (HttpContext.Request.Method == "POST")
            {
                ModelState.Clear(); // Causes Model Validation to be skipped and reset for next entry
                CollaborationName = "";
                CollaborationNotes = "";
            }
            return Page();
        }
    }
}

SignalRChat/Pages/Columns.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SignalRChat.Pages
{
    public class ColumnsModel : PageModel
    {
        public int column1 { get; set; }
        public int column2 { get; set; }
        public string FileName { get; set; }



        public IActionResult OnGet(string fileName)
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                FileName = fileName;
                return Page();
            }
            else
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("Login");
            }
        }


        public IActionResult OnPost(int column1, int column2, string fileName)
        {
            // Validate and process the column values
            // You can also perform additional validation if needed

            // Redirect to another page passing the required parameters
            return RedirectToPage("/RevenueAnalysis", new { fileName, column1, column2 });
        }
    }
}

SignalRChat/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SignalRChat.Pages.DataClasses;
using SignalRChat.Pages.DB;
using System.Data.SqlClient;

namespace SignalRChat.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public KnowledgeItem NewKnowledgeItem { get; set; }
        public List<KnowledgeItem> KnowledgeItemList { get; set; } = new List<KnowledgeItem>();

        public List<Users> UsersList { get; set; } = new List<Users>();

        public string SearchTerm { get; set; }
        public List<PublicDocument> Doc { get; set; } = new List<PublicDocument>();

        public List<PublicPreviousSpendingAnalysis> PublicPreviousSpendingAnalysis { get; set; } = new List<PublicPreviousSpendingAnalysis>();

        public IActionResult OnGet()
        {
            HttpContext.Session.Clear();
            // Populate UsersList with user data from the database
            SqlDataReader userReader = DBClass.GetAllUsers();
            while (userReader.Read())
            {
                UsersList.Add(new Users
                {
                    UserID = Convert.ToInt32(userReader["UserID"]),
                    Username = userReader["Username"].ToString()
                });
            }
            userReader.Close();
            DBClass.CollabFusionDBConnection.Close();

            LoadAllKnowledge();
            LoadAllAnalysis();
            // Close your connection in DBClass
            DBClass.CollabFusionDBConnection.Close();
            return Page();

        }


        public IActionResult OnPostSearch(String SearchTerm)
        {
            if (!string.IsNullOrEmpty(SearchTerm))
            {
                Doc = DB.DBClass.SearchPublicKnowledge(SearchTerm);

            }
            else
            {
                LoadAllKnowledge();
                //DBClass.CollabFusionDBConnection.Close();

            }
            return Page();
        }
        private void LoadAllKnowledge()
        {

            SqlDataReader reader = DBClass.GeneralReaderQuery("SELECT * FROM PublicDocument Order By DateAdded Desc");

            while (reader.Read())
            {
                Doc.Add(new PublicDocument
                {
                    Id = Convert.ToInt32(reader["Id"]),
                    FileName = reader["FileName"].ToString(),
                    FileData = (byte[])reader["FileData"],
                    DateAdded = Convert.ToDateTime(reader["DateAdded"]),
                    AnalysisType = reader["AnalysisType"].ToString()
                });
            }
            reader.Close();
            DB.DBClass.CollabFusionDBConnection.Close();

        }

        private void LoadAllAnalysis()
        {
            SqlDataReader reader = DBClass.GeneralReaderQuery("SELECT * FROM PublicPreviousSpendingAnalysis Order By SpendingAnalysisDate Desc");

            while (reader.Read())
            {
                PublicPreviousSpendingAnalysis.Add(new PublicPreviousSpendingAnalysis
                {
                    SpendingAnalysisID = Convert.ToInt32(reader["SpendingAnalysisID"]),
                    SpendingAnalysisName = reader["SpendingAnalysisName"].ToString(),
                    SpendingAnalysisDescription = reader["SpendingAnalysisDescription"].ToString(),
                    BasedOffOf = reader["BasedOffOf"].ToString(),
                    SpendingAnalysisDate = Convert.ToDateTime(reader["SpendingAnalysisDate"]),
                    Column1 = Convert.ToInt32(reader["Column1"]),
                    Column2 = Convert.ToInt32(reader["Column2"])
                });
            }
            reader.Close();
            DB.DBClass.CollabFusionDBConnection.Close();
        }

        public IActionResult OnPost(int column1, int column2, string fileName)
        {
            // Validate and process the column values
            // You can also perform additional validation if needed

            // Redirect to another page passing the required parameters
            return RedirectToPage("/ViewPublicRevenueAnalysis", new { fileName, column1, column2 });
        }
    }
}

SignalRChat/Pages/KnowledgeLibrary.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Routing.Constraints;
using SignalRChat.Pages.DataClasses;
using SignalRChat.Pages.DB;
using System.Data.SqlClient;

namespace SignalRChat.Pages
{
    public class KnowledgeLibraryModel : PageModel
    {
        [BindProperty]
        public KnowledgeItem NewKnowledgeItem { get; set; }
        public List<KnowledgeItem> KnowledgeItemList { get; set; } = new List<KnowledgeItem>();

        public List<Users> UsersList { get; set; } = new List<Users>();

        public string SearchTerm { get; set; }
        public List<Document> Doc { get; set; } = new List<Document>();
        //

        public List<PreviousSpendingAnalysis> PreviousSpendingAnalysisList { get; set; } = new List<PreviousSpendingAnalysis>();

        [BindProperty]
        public IFormFile File { get; set; }

        [BindProperty]
        public string AnalysisType { get; set; }
        public string FileName { get; set; }

        public string FileData { get; set; }

        public string DateAdded { get; set; }

        public string AnalysesType { get; set; }
        // Connection Object at Data Field Level
        public static SqlConnection CollabFusionDBConnection = new SqlConnection();

        // Connection String - How to find and connect to DB
        private static readonly string CollabFusionDBConnString = "Server=sharpmindsdb1.database.windows.net,1433;" + "Database=Lab3;" + "User Id=gwen;" + "Password=sharpminds1!;" + "Encrypt=True;" + "TrustServerCertificate=True";


        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("username") != null)
            {
                // Populate UsersList with user data from the database
                SqlDataReader userReader = DBClass.GetAllUsers();
                while (userReader.Read())
                {
                    UsersList.Add(new Users
                    {
                        UserID = Convert.ToInt32(userReader["UserID"]),
                        Username = userReader["Username"].ToString()
                    });
                }
                userReader.Close();
                DBClass.CollabFusionDBConnection.Close();

                LoadAllKnowledge();
                // Close your connection in DBClass
                DBClass.CollabFusionDBConnection.Close();

                SqlDataReader previousAnalysisReader = DBClass.GetAllPreviousSpendingAnalysis();
                while (previousAnalysisReader.Read())
                {
                    PreviousSpendingAnalysisList.Add(new PreviousSpendingAnalysis
                    {
                        SpendingAnalysisID = Convert.ToInt32(previousAnalysisReader["SpendingAnalysisID"]),
                        SpendingAnalysisName = previousAnalysisReader["SpendingAnalysisName"].ToString(),
                        SpendingAnalysisDescription = previousAnalysisReader["SpendingAnalysisDescription"].ToString(),
                        BasedOffOf = previousAnalysisReader["BasedOffOf"].ToString(),
                        SpendingAnalysisDate = Convert.ToDateTime(previousAnalysisReader["SpendingAnalysisDate"]).Date,
                        Column1 = Convert.ToInt32(previousAnalysisReader["Column1"]),
                        Column2 = Convert.ToInt32(previousAnalysisReader["Column2"])
                    });
                }
                DBClass.CollabFusionDBConnection.Close();
                return Page();
            }
            else
            {
                HttpContext.Session.SetString("LoginError", "You must login to access that page!");
                return RedirectToPage("Index");
            }

        }

        public IActionResult OnPost(int column1, int column2, string fileName)
        {
            // Validate and process the column values
            // You can also perform additional validation if needed

            // Redirect to another page passing the required parameters
            return RedirectToPage("/ViewRevenueAnalysis", new { fileName, column1, column2 });
        }


        public IActionResult OnPostSearch(String SearchTerm)
        {
            if (!string.IsNullOrEmpty(SearchTerm))
            {
                Doc = DB.DBClass.SearchKnowledge(SearchTerm);

            }
            else
            {
                LoadAllKnowledge();
                //DBClass.CollabFusionDBConnection.Close();

            }
            return Page();
        }
        private void LoadAllKnowledge()
        {
            //Document LOGIC START
            //Document LOGIC START
            SqlDataReader reader = DBClass.GeneralReaderQuery("SELECT * FROM Document Order By DateAdded Desc");

            while (reader.Read())
            {
                Doc.Add(new Document
                {
                    Id = Convert.ToInt32(reader["Id"]),
                    FileName = reader["FileName"].ToString(),
                    FileData = (byte[])reader["FileData"],
                    DateAdded = Convert.ToDateTime(reader["DateAdded"]),
                    AnalysisType = reader["AnalysisType"].ToString()
                });
            }
            reader.Close();
            DB.DBClass.CollabFusionDBConnection.Close();

        }

        //public IActionResult OnPostPush(int Id)
        //{
        //    //var reader = new DBClass.PublicKnowledgeReader(id);
        //    //FileName = reader.FileName;
        //    ////Document documentToPush = Doc.Find(doc => doc.Id == id);
        //    //if (File != null && File.Length > 0)
        //    //{
        //    //    using (var memoryStream = new MemoryStream())
        //    //    {
        //    //        File.CopyTo(memoryStream);
        //    //        var fileData = memoryStream.ToArray();

        //    //        var document = new PublicDocument
        //    //        {
        //    //            FileName = Path.GetFileName(File.FileName),
        //    //            FileData = fileData,
        //    //            DateAdded = DateTime.Now,
        //    //            AnalysisType = AnalysisType
        //    //        };

        //    //        DBClass.InsertPublicDocument(document);
        //    //        DBClass.CollabFusionDBConnection.Close();

        //    //        // Set success message in TempData
        //    //        TempData["UploadSuccessMessage"] = "File uploaded successfully.";


        //    //        return Page();
        //    //        //return RedirectToPage("/EnteredCollaboration", new { collaborationid = HttpContext.Session.GetInt32("collabid") });
        //    //    }
        //    //}
        //    //return Page();


        //    List<PublicDocument> SearchedDocument = new List<PublicDocument>();

        //    using (SqlConnection connection = new SqlConnection(CollabFusionDBConnString))
        //    {
        //        connection.Open();
        //        string sqlQuery = "SELECT * FROM PublicDocument WHERE Id LIKE @Id";
        //        using (SqlCommand command = new SqlCommand(sqlQuery, connection))
        //        {
        //            command.Parameters.AddWithValue("@Id", "%" + Id + "%");
        //            using (SqlDataReader reader = command.ExecuteReader())
        //            {
        //                while (reader.Read())
        //                {
        //                    PublicDocument knowledge = new PublicDocument
        //                    {
        //                        Id = Convert.ToInt32(reader["Id"]),
        //                        FileName = reader["FileName"].ToString(),
        //                        FileData = (byte[])reader["FileData"],
        //                        DateAdded = Convert.ToDateTime(reader["DateAdded"]),
        //                        AnalysisType = reader["AnalysisType"].ToString()
        //                    };
        //                    SearchedDocument.Add(knowledge);
        //                }
        //            }
        //        }
        //    }
        //    //return (IActionResult)SearchedDocument;
        //    CollabFusionDBConnection.Close();



        //    string sqlQuery2 = "INSERT INTO PublicDocument (FileName, FileData, DateAdded, AnalysisType) VALUES (@FileName, @FileData, @DateAdded, @AnalysisType)";

        //    using (SqlCommand cmdDocInsert = new SqlCommand(sqlQuery2, CollabFusionDBConnection))
        //    {
        //        cmdDocInsert.Parameters.AddWithValue("@FileName", FileName);
        //        cmdDocInsert.Parameters.AddWithValue("@FileData", FileData);
        //        cmdDocInsert.Parameters.AddWithValue("@DateAdded", DateAdded);
        //        cmdDocInsert.Parameters.AddWithValue("@AnalysisType", AnalysisType);

        //        //CollabFusionDBConnection.Open();
        //        //cmdDocInsert.ExecuteNonQuery();
        //        //CollabFusionDBConnection.Close();

        //       // SqlCommand cmdRead = new SqlCommand();
        //        cmdDocInsert.Connection = CollabFusionDBConnection;
        //        cmdDocInsert.Connection.ConnectionString = CollabFusionDBConnString;
        //        cmdDocInsert.CommandText = sqlQuery2;
        //        cmdDocInsert.Connection.Open();

        //        cmdDocInsert.ExecuteNonQuery();
        //    }

        //    return Page();

        //}


        public IActionResult OnPostPush(int Id)
        {
            List<PublicDocument> SearchedDocument = new List<PublicDocument>();

            // Step 1: Read data from the source table and close the SqlDataReader
            using (SqlConnection connection = new SqlConnection(CollabFusionDBConnString))
            {
                connection.Open();
                string selectQuery = "SELECT * FROM Document WHERE Id = @Id";
                using (SqlCommand command = new SqlCommand(selectQuery, connection))
                {
                    command.Parameters.AddWithValue("@Id", Id);

SignalRChat/Pages/AllSteps.cshtml
@page
@model SignalRChat.Pages.AllStepsModel
@{
    ViewData["username"] = HttpContext.Session.GetString("username");
    ViewData["collabid"] = HttpContext.Session.GetInt32("collabid");

}
<br />
<h1>View Your Plans</h1>
<hr />

@foreach (var plan in Model.PlanList)
{
    <br />
    <h4>All Steps for @plan.PlanName</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Step Title</th>
                <th>Step Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var PlanStep in Model.MatchingPlanStepList)
            {
                if (PlanStep.PlanID == plan.PlanID)
                {
                    <tr>
                        <td>@PlanStep.StepTitle</td>
                        <td>@PlanStep.StepDescription</td>
                    </tr>
                }
                
            }
        </tbody>
    </table>
}

SignalRChat/Pages/CollabSpace.cshtml
@page
@model SignalRChat.Pages.CollabSpaceModel
@{
    ViewData["username"] = HttpContext.Session.GetString("username");
}

<br />
<h3>Please Enter the Information</h3>
<form asp-page="CollabSpace">
    <div class="form-group">
        <label class="form-label">Collaboration Name</label>
        <input asp-for="CollaborationName" class="form-control" placeholder="Enter Collaboration Name">
        <span asp-validation-for="CollaborationName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="form-label">Collaboration Notes</label>
        <textarea asp-for="CollaborationNotes" rows="4" placeholder="Enter Notes"></textarea>
        <span asp-validation-for="CollaborationNotes" class="text-danger"></span>
    </div>
    <button type="submit" class="btn" style="background-color: #293A7F; color: white;">Create New Collaboration</button>
    <button asp-page="CollabSpace" asp-page-handler="PopulateButton" class="btn btn-secondary" formnovalidate>Populate</button>
    <button asp-page="CollabSpace" asp-page-handler="ClearButton" class="btn btn-secondary" formnovalidate>Clear</button>

</form>
<br />
    <a class="btn" style="background-color: #293A7F; color: white;" asp-page="/CollabHub">&#8592; Back</a>

SignalRChat/Pages/KnowledgeLibrary.cshtml
@page
@model SignalRChat.Pages.KnowledgeLibraryModel
@{
    ViewData["username"] = HttpContext.Session.GetString("username");
    ViewData["collabid"] = HttpContext.Session.GetInt32("collabid");
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="./css/carousel.css" />
    <style>
        .accordion {
            background-color: #293A7F;
            color: #fff;
            cursor: pointer;
            padding: 18px;
            width: 100%;
            text-align: left;
            border: none;
            outline: none;
            transition: background-color 0.4s;
        }

            .accordion:hover {
                background-color: #1d2959;
            }

        .panel {
            padding: 0 18px;
            overflow: hidden;
            transition: max-height 0.2s ease-out;
            max-height: 0;
        }

            .panel.active {
                max-height: 500px; /* Adjust this value according to your content height */
            }
    </style>
</head>
<body>
    <br />
    <a class="btn" style="background-color: #293A7F; color: white;" asp-page="/CollabHub">&#8592; Back</a>
    <br />
    <br />
    <button class="accordion">Uploaded Documents</button>
    <div class="panel">
        <br />
        <form method="post" asp-page-handler="Search">
            <label asp-for="SearchTerm" style="display: block;">Search Documents:</label>
            <input placeholder="Enter File Name" type="text" asp-for="SearchTerm" style="border-style: solid;" class="form-control" />
            <br />
            <button type="submit" class="btn" style="background: #293A7F; color: white;">Search</button>
            <a asp-page="KnowledgeLibrary" class="btn btn-secondary">Clear</a>
        </form>
        <br />
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>File Name</th>
                        <th>Date Uploaded</th>
                        <th>Command</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var document in Model.Doc)
                    {
                        <tr>
                            <td>@document.FileName</td>
                            <td>@document.DateAdded.ToShortDateString()</td>
                            <td>
                                <div style="display: flex; gap: 1em;">
                                    <button class="btn" style="background: #293A7F; color: white;" onclick="downloadDocument('@document.FileName', '@(document.FileData != null ? Convert.ToBase64String(document.FileData) : null)')">Download</button>
                                    <form method="post" asp-page-handler="Push" asp-route-id="@document.Id">
                                        <button type="submit" class="btn btn-secondary">Push</button>
                                    </form>
                                </div>
                            </td>
                            
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <button class="accordion">Previous Regression Analysis</button>
    <div class="panel">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Analysis Name</th>
                        <th>Analysis Description</th>
                        <th>Based Off Of</th>
                        <th>Created Date</th>
                        <th>Command</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var analysis in Model.PreviousSpendingAnalysisList)
                    {
                        <tr>
                            <td>@analysis.SpendingAnalysisName</td>
                            <td>@analysis.SpendingAnalysisDescription</td>
                            <td>@analysis.BasedOffOf</td>
                            <td>@analysis.SpendingAnalysisDate.ToShortDateString()</td>
                            <td>
                                <form method="post">
                                    <button type="submit" asp-route-fileName="@analysis.BasedOffOf" asp-route-SpendingAnalysisID="@analysis.SpendingAnalysisID" asp-route-column1="@analysis.Column1" asp-route-column2="@analysis.Column2" class="btn" style="background-color: #293A7F; color: white;">View Analysis</button>
                                </form>
                                <form method="post" asp-page-handler="PushAnalysis" asp-route-spendinganalysisid="@analysis.SpendingAnalysisID">
                                    <button type="submit" class="btn btn-secondary">Push</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <!-- JavaScript section -->
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var acc = document.getElementsByClassName("accordion");

            // Function to toggle accordion panels
            function togglePanel(panel) {
                var isActive = panel.classList.toggle("active");
                var content = panel.nextElementSibling;
                if (isActive) {
                    content.style.maxHeight = content.scrollHeight + "px";
                } else {
                    content.style.maxHeight = null;
                }
            }

            // Add click event listeners to accordion buttons
            for (var i = 0; i < acc.length; i++) {
                acc[i].addEventListener("click", function () {
                    togglePanel(this);
                });
            }

            // Open the first accordion on page load
            if (acc.length > 0) {
                togglePanel(acc[0]);
            }
        });

        function downloadDocument(fileName, fileData) {
            if (fileData !== null) {
                // Create a blob from the base64 encoded file data
                var byteCharacters = atob(fileData);
                var byteNumbers = new Array(byteCharacters.length);
                for (var i = 0; i < byteCharacters.length; i++) {
                    byteNumbers[i] = byteCharacters.charCodeAt(i);
                }
                var byteArray = new Uint8Array(byteNumbers);
                var blob = new Blob([byteArray], { type: 'application/octet-stream' });

                // Create a link element and trigger a download
                var link = document.createElement('a');
                link.href = window.URL.createObjectURL(blob);
                link.download = fileName;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
            } else {
                alert("File not available for download.");
            }
        }
    </script>

    <!-- Display success message if it exists in TempData -->
    @if (TempData["UploadSuccessMessage"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["UploadSuccessMessage"]
        </div>
    }
</body>
</html>

SignalRChat/Pages/PlanStep.cshtml
@page
@model SignalRChat.Pages.PlanStepModel
@{
    ViewData["username"] = HttpContext.Session.GetString("username");
}

<h2>Create a Step</h2>

<form asp-page="PlanStep">
    <select asp-for="NewPlanStep.PlanID" class="form-control">
        <option selected disabled>Choose A Plan ...</option>
        @foreach (var plan in Model.PlanList)
        {
            <option value="@plan.PlanID">@plan.PlanName</option>
        }
    </select>
    <label for="stepTitle">Step Title:</label>
    <br>
    <input asp-for="NewPlanStep.StepTitle" class="form-control" required>

    <br><br>

    <label for="stepDescription">Step Description:</label>
    <br>
    <textarea asp-for="NewPlanStep.StepDescription" rows="4" class="form-control" required></textarea>

    <br><br>

    <button type="submit" class="btn" style="background-color: #293A7F; color: white;">Add Step to Plan</button>
    <button asp-page="PlanStep" asp-page-handler="PopulateButton" class="btn btn-secondary" formnovalidate>Populate</button>
    <button asp-page="PlanStep" asp-page-handler="ClearButton" class="btn btn-secondary" formnovalidate>Clear</button>
</form>

SignalRChat/Pages/SWOT.cshtml
@page
@model SignalRChat.Pages.SWOTModel
@{
    ViewData["username"] = HttpContext.Session.GetString("username");
    ViewData["collabid"] = HttpContext.Session.GetInt32("collabid");
}

<br />
<h3>Create a SWOT Analysis</h3>

<form asp-page="SWOT">

    <div class="form-group">
        <label class="form-label">SWOT Title</label>
        <input asp-for="NewKnowledgeItem.KnowledgeTitle" class="form-control" placeholder="Enter SWOT Title"> @*Dont need type or name for inputs*@
        <span asp-validation-for="NewKnowledgeItem.KnowledgeTitle" class="text-danger"></span>                     @*For invalid form submissions*@
    </div>

    <div class="form-group">
        <label class="form-label">SWOT Subject</label>
        <input asp-for="NewKnowledgeItem.KnowledgeSubject" class="form-control" placeholder="Enter Knowledge Subject">
        <span asp-validation-for="NewKnowledgeItem.KnowledgeSubject" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Strengths</label>
        <textarea asp-for="NewKnowledgeItem.Strengths" class="form-control" rows="3" placeholder="Enter Strengths"></textarea>
        <span asp-validation-for="NewKnowledgeItem.Strengths" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Weaknesses</label>
        <textarea asp-for="NewKnowledgeItem.Weaknesses" class="form-control" rows="3" placeholder="Enter Weaknesses"></textarea>
        <span asp-validation-for="NewKnowledgeItem.Weaknesses" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Opportunities</label>
        <textarea asp-for="NewKnowledgeItem.Opportunities" class="form-control" rows="3" placeholder="Enter Opportunities"></textarea>
        <span asp-validation-for="NewKnowledgeItem.Opportunities" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Threats</label>
        <textarea asp-for="NewKnowledgeItem.Threats" class="form-control" rows="3" placeholder="Enter Threats"></textarea>
        <span asp-validation-for="NewKnowledgeItem.Threats" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="form-label">Date</label>
        <input asp-for="NewKnowledgeItem.KNDate" class="form-control">
        <span asp-validation-for="NewKnowledgeItem.KNDate" class="text-danger"></span>
    </div>

    <br />
    <button type="submit" class="btn" style="background-color: #293A7F; color: white;">Submit</button>
    <button asp-page="SWOT" asp-page-handler="PopulateButton" class="btn btn-secondary" formnovalidate>Populate</button>
    <button asp-page="SWOT" asp-page-handler="ClearButton" class="btn btn-secondary" formnovalidate>Clear</button>
</form>